---
name: CI

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  cpython:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-uv

      - name: Install Dependencies and library
        if: steps.cache.outputs.cache-hit != 'true'
        run: uv pip install --system -e .[dev]

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
